In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/Siva/Projects/Amazon Sales analysis/Amazon Sale Report.csv")
df.head()

C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\3589316273.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/Siva/Projects/Amazon Sales analysis/Amazon Sale Report.csv")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

## Data Inspection

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [ ]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [ ]:
df.isna().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [ ]:
df.shape

(128975, 24)

In [ ]:
df.duplicated().sum()

0

- The data contains approximately more than 50% missing values in some columns
- There is no dupliicated data.

## Data Cleaning

In [8]:
df_columns = df.columns
df_columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [9]:
df1 = df[['Order ID','Date', 'Status', 'Fulfilment', 'Sales Channel ',
          'ship-service-level', 'Category', 'Size', 'Courier Status', 'Qty',
          'Amount', 'ship-city','ship-state', 'B2B', 'fulfilled-by']]
df1.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,Amount,ship-city,ship-state,B2B,fulfilled-by
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Set,S,NaN,0,647.62,MUMBAI,MAHARASHTRA,False,Easy Ship
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,kurta,3XL,Shipped,1,406.00,BENGALURU,KARNATAKA,False,Easy Ship
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,kurta,XL,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,True,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Western Dress,L,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,False,Easy Ship
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Top,3XL,Shipped,1,574.00,CHENNAI,TAMIL NADU,False,NaN

In [10]:
df1.isna().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Category                  0
Size                      0
Courier Status         6872
Qty                       0
Amount                 7795
ship-city                33
ship-state               33
B2B                       0
fulfilled-by          89698
dtype: int64

In [11]:
df1['Courier Status'] = df['Courier Status'].fillna('Unshipped')
df1['Amount'] = df['Amount'].fillna(0)
df1['ship-city'] = df['ship-city'].fillna('Unknown')
df1['ship-state'] = df['ship-state'].fillna('Unknown')
df1['fulfilled-by'] = df['fulfilled-by'].fillna('Self Ship')

C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\904355965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Courier Status'] = df['Courier Status'].fillna('Unshipped')
C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\904355965.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Amount'] = df['Amount'].fillna(0)
C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\904355965.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ship-city'] = df['ship-city'].fillna('Unknown')
C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\904355965.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ship-state'] = df['ship-state'].fillna('Unknown')
C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\904355965.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['fulfilled-by'] = df['fulfilled-by'].fillna('Self Ship')

In [12]:
df1.isna().sum()

Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Category              0
Size                  0
Courier Status        0
Qty                   0
Amount                0
ship-city             0
ship-state            0
B2B                   0
fulfilled-by          0
dtype: int64

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  object
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Category            128975 non-null  object
 7   Size                128975 non-null  object
 8   Courier Status      128975 non-null  object
 9   Qty                 128975 non-null  int64
 10  Amount              128975 non-null  float64
 11  ship-city           128975 non-null  object
 12  ship-state          128975 non-null  object
 13  B2B                 128975 non-null  bool
 14  fulfilled-by        128975 non-null  object
dtypes: bool(1), float64(1), int64(1), object(12)
memory usage: 13.9+ MB

In [14]:
df1['Date'] = pd.to_datetime(df['Date'])

C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\3690556775.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1['Date'] = pd.to_datetime(df['Date'])
C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\3690556775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Date'] = pd.to_datetime(df['Date'])

In [15]:
df1['Date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 128975 entries, 0 to 128974
Series name: Date
Non-Null Count   Dtype
--------------   -----
128975 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1007.7 KB

In [16]:
df1['Status'] = df1['Status'].replace('Shipped - Delivered to Buyer','Delivered')

C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\126731022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Status'] = df1['Status'].replace('Shipped - Delivered to Buyer','Delivered')

In [17]:
df1['Month'] = df1['Date'].dt.month_name()
df1['ship-city'] = df1['ship-city'].str.upper()
df1['ship-state'] = df1['ship-state'].str.upper()

C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\1619250424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Month'] = df1['Date'].dt.month_name()
C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\1619250424.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ship-city'] = df1['ship-city'].str.upper()
C:\Users\Siva\AppData\Local\Temp\ipykernel_32384\1619250424.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ship-state'] = df1['ship-state'].str.upper()

In [18]:
df1.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Category', 'Size', 'Courier Status', 'Qty',
       'Amount', 'ship-city', 'ship-state', 'B2B', 'fulfilled-by', 'Month'],
      dtype='object')

In [19]:
df1 = df1[['Order ID', 'Date', 'Month', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Category', 'Size', 'Courier Status', 'Qty',
       'Amount', 'ship-city', 'ship-state', 'B2B', 'fulfilled-by']]

In [20]:
df1.head()

,Order ID,Date,Month,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,Amount,ship-city,ship-state,B2B,fulfilled-by
0,405-8078784-5731545,2022-04-30,April,Cancelled,Merchant,Amazon.in,Standard,Set,S,Unshipped,0,647.62,MUMBAI,MAHARASHTRA,False,Easy Ship
1,171-9198151-1101146,2022-04-30,April,Delivered,Merchant,Amazon.in,Standard,kurta,3XL,Shipped,1,406.00,BENGALURU,KARNATAKA,False,Easy Ship
2,404-0687676-7273146,2022-04-30,April,Shipped,Amazon,Amazon.in,Expedited,kurta,XL,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,True,Self Ship
3,403-9615377-8133951,2022-04-30,April,Cancelled,Merchant,Amazon.in,Standard,Western Dress,L,Unshipped,0,753.33,PUDUCHERRY,PUDUCHERRY,False,Easy Ship
4,407-1069790-7240320,2022-04-30,April,Shipped,Amazon,Amazon.in,Expedited,Top,3XL,Shipped,1,574.00,CHENNAI,TAMIL NADU,False,Self Ship

- The data is cleaned and transformed to analysis.
- The new attributes (Month) is added.
- The Transformed data is saved on new file.

In [21]:
df1.to_csv('Amazon Sale Report-Transformed.csv', index=False)